export { Footer } from "./footer/Footer"
export { TopMenu } from "./topMenu/TopMenu"
export { Search } from "./topMenu/Search"
export { title } from "./font/fonts"

export { CategoriesPopular } from "./home/CategoriesPopular"
export { SpecialOffersOne } from "./home/SpecialOffersOne"
export { AddressForm } from "./address/AddressForm"
export { ServiceInfo } from "./home/ServiceInfo"
export { DownloadApp } from "./home/DownloadApp"
export { TopMenuAuth } from "./auth/TopMenuAuth"
export { SectionTwo } from "./home/SectionTwo"
export { Header } from "./home/Header"
