import type { Product } from "../interface";


export const productsData: Product[] = [
    // VEGETALES
    {
        image: "/products/pepino.webp",
        title: "Pepino de invernadero 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "vegetales",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/tomate.webp",
        title: "Tomates Beefsteak grandes 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "vegetales",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/pimenton.webp",
        title: "Pimiento rojo de invernadero 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "vegetales",
        offer: false,
        price: 79.50,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/zanahoria.webp",
        title: "Zanahorias Lancaster 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "vegetales",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/aguacate.webp",
        title: "Aguacates Hass en su punto 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "vegetales",
        offer: true,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    // FRUTAS
    {
        image: "/products/platano.webp",
        title: "Plátano 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "frutas",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/naranja.webp",
        title: "Naranja Navel 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "frutas",
        offer: false,
        price: 76.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/fresas.webp",
        title: "Fresas 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "frutas",
        offer: true,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/manzana.webp",
        title: "Manzana magna 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "frutas",
        offer: false,
        price: 37.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pera.webp",
        title: "Pera Bartlett 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "frutas",
        offer: false,
        price: 38.50,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/bistec.webp",
        title: "Bistec Al Minuto 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "carne y aves",
        offer: false,
        price: 139.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pechuga.webp",
        title: "Pechugas de pollo sin hueso 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "carne y aves",
        offer: false,
        price: 129.99,
        stock: 50,
        ventas: 0
    },

    {
        image: "/products/filete.webp",
        title: "Filete de res 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "carne y aves",
        offer: false,
        price: 139.99,
        stock: 50,
        ventas: 0
    },

    {
        image: "/products/salchicha.webp",
        title: "Salchicha italiana de pollo 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "carne y aves",
        offer: false,
        price: 119.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/muslo.webp",
        title: "Muslos de pollo sin hueso 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "carne y aves",
        offer: true,
        price: 76.59,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/camarones.webp",
        title: "Camarones crudo grande 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pescados y mariscos",
        offer: false,
        price: 379.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/mejillones.webp",
        title: "Mejillones Iceberg 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pescados y mariscos",
        offer: false,
        price: 389.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/fileteAtun.webp",
        title: "Filete de atún 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pescados y mariscos",
        offer: true,
        price: 399.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/fileteSalmon.webp",
        title: "Filete de salmón real 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pescados y mariscos",
        offer: false,
        price: 399.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/fileteFletan.webp",
        title: "Filete de Fletán Noruego 0.5 kg.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pescados y mariscos",
        offer: false,
        price: 1,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/mantequilla.webp",
        title: "Mantequilla estilo europeo 8 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 82.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/lecheEntera.webp",
        title: "Leche entera galón 64 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 38.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/lecheReducida.webp",
        title: "Leche reducida al 2% 64 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 38.50,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/lecheChocolate.webp",
        title: "Envase de leche con chocolate",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 12.00,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/huevosBlancos.webp",
        title: "Huevo blanco grande natural",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 10.50,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/huevoCafe.webp",
        title: "Huevo café medio natural",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/quesoCrema.webp",
        title: "Queso crema para untar 8 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/quesoFeta.webp",
        title: "Queso feta rallado 4 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/yogurGRIEGO.webp",
        title: "Yogur griego con fresa en el fondo",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 12.49,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/yogurNatural.webp",
        title: "Yogur Natural con cereza incluida",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "lácteos y huevos",
        offer: false,
        price: 12.49,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/baguete.webp",
        title: "Baguette fresco natural 12 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/panecillo.webp",
        title: "Panecillos frescos de brioche 4 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/bagel.webp",
        title: "Bagels enteros, 6 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/panTrigo.webp",
        title: "Pan 100% de trigo integral 24 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 76.59,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/panBlanco.webp",
        title: "Pan blanco de molde 24 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: true,
        price: 76.59,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/croisan.webp",
        title: "Croissants para hornear 4 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 119.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/croisanChocolate.webp",
        title: "Croissants de chocolate para hornear 4 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pastelPlatano.webp",
        title: "Pastel de plátano y chocolate",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/brownies.webp",
        title: "Brownies de chocolate con dulce de leche",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/galletas.webp",
        title: "Galletas horneadas con chocolate 4 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "panadería",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pastaRigati.webp",
        title: "Pasta penne Rigati 350 gr.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 37.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/pastaTallarines.webp",
        title: "Pasta tallarines Rigati 350 gr.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/espaguetis.webp",
        title: "Espaguetis delgados 300 gr.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: true,
        price: 37.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pastaOrejones.webp",
        title: "Pasta en forma de orejones",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/espagueti.webp",
        title: "Espagueti nº 7",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/arrozLargo.webp",
        title: "Arroz Basmati de grano largo 8.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 119.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/arrozClasico.webp",
        title: "Arroz Basmati clásico 8.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 119.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/arrozIntegral.webp",
        title: "Arroz integral bio",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/arrozNegro.webp",
        title: "Arroz negro bio",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/arrozBlanco.webp",
        title: "Arroz blanco bio",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "pastas y granos",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cerealCorn.webp",
        title: "Cereal Corn Flakes 14.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/cerealChocolate.webp",
        title: "Cereal de chocolate bio 12.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cerealCenteno.webp",
        title: "Cereal de centeno bio 12.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cerealGranola.webp",
        title: "Cereal de granola, avena y miel 16 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cerealAvena.webp",
        title: "Cereal de granola, avena y frutas 16 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/papasFritas.webp",
        title: "Papas fritas extra picantes",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/papasPicates.webp",
        title: "Papas fritas picantes",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/heladosPzas.webp",
        title: "Paquete variado de helados, 5 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 129.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/chocolate.webp",
        title: "Barra de chocolate con leche 35%",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/chocolateNegro.webp",
        title: "Barra de chocolate negro 35%",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "comida",
        subCategory: "cereales y botanas",
        offer: false,
        price: 1,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/teVerde.webp",
        title: "Té verde 16 peas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "té",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/teBlanco.webp",
        title: "Té blanco 16 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "té",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/teNegro.webp",
        title: "Té negro 16 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "té",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/teHierbas.webp",
        title: "Té de hierbas 16 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "té",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/teManzanilla.webp",
        title: "Té de manzanilla 16 pzas.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "té",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/cafeTostado.webp",
        title: "Café tostado medio de Brasil",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "café",
        offer: false,
        price: 109.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/cafeMolido.webp",
        title: "Café molido de Colombia",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "café",
        offer: false,
        price: 169.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cafeGrano.webp",
        title: "Café en grano mezcla Vietnam",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "café",
        offer: false,
        price: 179.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cafeDescafeinado.webp",
        title: "Café soluble descafeinado Aromas",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "café",
        offer: true,
        price: 129.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cafeSoluble.webp",
        title: "Café soluble Aromas",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "café",
        offer: false,
        price: 129.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/refrescoCola.webp",
        title: "Refresco sabor cola",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "bebidas sin alcohol",
        offer: false,
        price: 29.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/refrescoLimon.webp",
        title: "Refresco sabor limón",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "bebidas sin alcohol",
        offer: false,
        price: 29.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/refrescoFrambuesa.webp",
        title: "Refresco sabor frambuesa",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "bebidas sin alcohol",
        offer: false,
        price: 29.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/agua.webp",
        title: "Pureza botella de agua 1892 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "bebidas sin alcohol",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/jugoNaranja.webp",
        title: "Jugo de naranja fresco 1892 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "bebidas sin alcohol",
        offer: true,
        price: 119.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cervezaNegra.webp",
        title: "Cerveza negra en botella 470 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "cerveza",
        offer: true,
        price: 36.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cervezaClara.webp",
        title: "Cerveza clara en botella 470 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "cerveza",
        offer: false,
        price: 36.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cervezaPanela.webp",
        title: "Cerveza Pale Ale en botella 470 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "cerveza",
        offer: false,
        price: 36.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/cervezaTrigo.webp",
        title: "Cerveza de trigo en botella 470 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "cerveza",
        offer: false,
        price: 36.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cervezaPremiu,.webp",
        title: "Cerveza Premium en botella 470 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "cerveza",
        offer: false,
        price: 36.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/chinon.webp",
        title: "Chinon Rosa 750 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "vino",
        offer: true,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cabernet.webp",
        title: "Cabernet Sauvignon 750 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "vino",
        offer: false,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/vinoBlanco.webp",
        title: "Sauvignon Blanc 750 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "vino",
        offer: false,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cgardonnay.webp",
        title: "Chardonnay 750 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "vino",
        offer: false,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/vinoRosa.webp",
        title: "Rosa Lux 750 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "bebidas",
        subCategory: "vino",
        offer: true,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/tablaCorta.webp",
        title: "Tabla de cortar de madera",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/bombillaLed.webp",
        title: "Bombilla Led 12W",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 12.00,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/bombillaFluorecente.webp",
        title: "Bombilla fluorescente 26W",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 12.00,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/tazonVidrio.webp",
        title: "Tazón de vidrio",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 229.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/untesiliosCocina.webp",
        title: "Utensilios de cocina de madera",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: true,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/ralladorMetal.webp",
        title: "Rallador de metal",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/sarten.webp",
        title: "Sartén con tapa",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: true,
        price: 229.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/tazonesMadera.webp",
        title: "Set de 3 tazones de madera",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 219.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cuchillos.webp",
        title: "Set de 5 cuchillos",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 269.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/aceiteOliva.webp",
        title: "Aceite de oliva",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "casa y cocina",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/limpiaPiso.webp",
        title: "Líquido limpia piso",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/blanqueador.webp",
        title: "Blanqueador",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/limpiadorSpray.webp",
        title: "Limpiador en spray multisuperficies",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 76.59,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/detergenteRopa.webp",
        title: "Detergente líquido para ropa",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/limpiaVajilla.webp",
        title: "Líquido para vajilla 32.5 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/limpiaCristal.webp",
        title: "Limpiacristales en spray",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: true,
        price: 76.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/detergentePolvo.webp",
        title: "Detergente en polvo para ropa",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/limpiadorMultiusos.webp",
        title: "Limpiador multiusos, limón",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/esponjaLimpiesa.webp",
        title: "Esponja de limpieza",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: false,
        price: 12.00,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/papelHigienico.webp",
        title: "Papel higiénico, 100 hojas",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "limpieza y hogar",
        subCategory: "productos de limpieza",
        offer: true,
        price: 82.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/maquillaje.webp",
        title: "Maquillaje",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 109.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/afeitarGel.webp",
        title: "Gel de afeitar",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 84.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/desodoranteSpray.webp",
        title: "Spray desodorante",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 79.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pastaDientes.webp",
        title: "Pasta de dientes blanqueadora 4 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: true,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/gelDucha.webp",
        title: "Gel de ducha 350 ml.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: true,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/tintePelo.webp",
        title: "Tinte de pelo",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 119.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/cremaMano.webp",
        title: "Crema de manos",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: true,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/champu.webp",
        title: "Champú, cabello normal 30 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/champuArcilla.webp",
        title: "Champú de arcilla reforzante 30 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: true,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/desinfetante.webp",
        title: "Desinfectante de manos",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "higiene personal",
        offer: false,
        price: 49.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pañalesSuperpack.webp",
        title: "Superpack de pañales talla 1.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 159.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pañalesAzul.webp",
        title: "Superpack de pañales de la talla 2.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 159.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/pañalesAmarrillo.webp",
        title: "Superpack de pañales talla 5.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 159.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/lechePolvo.webp",
        title: "Fórmula en polvo con hierro de 29 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: true,
        price: 79.00,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/lechePolvoInfantil.webp",
        title: "Fórmula infantil en polvo base leche 12.5 de oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 129.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/toallitas.webp",
        title: "Toallitas para bebé sin aroma 64 ct.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 0
    },
    {
        image: "/products/talcoBebe.webp",
        title: "Talco para bebé",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 39.99,
        stock: 50,
        ventas: 5
    },
    {
        image: "/products/pureFrutas.webp",
        title: "Pack de puré de frutas 4 oz.",
        description: "Detalle del producto. Lugar ideal para agregar más información sobre tu producto como su tamaño, materiales, instrucciones de uso y mantenimiento. También es un buen espacio para explicar lo especial que es tu producto y sus beneficios. A los compradores les gusta saber lo que van a recibir antes de comprarlo, así que proporciona toda la información posible para que puedan comprar con seguridad y confianza.",
        category: "cuidado personal",
        subCategory: "bebes",
        offer: false,
        price: 19.00,
        stock: 50,
        ventas: 0
    },

]
